services:
  backend:
    build: ./backend
    ports:
      - "4100:4100"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
